<a href="https://colab.research.google.com/github/claudiaesnarrizaga/APRENDIZAJE_AUTOMATICO_23_24/blob/main/0%20INTRODUCCION/0.3.%20Vectores%20y%20matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
lista = [5,6,9,8,7,4,65,2,2,56,46,54]
print(lista)

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]


In [2]:
2 in lista

True

In [3]:
35 in lista

False

In [4]:
lista[0]

5

In [5]:
lista[-1]

54

In [6]:
lista[2:4]

[9, 8]

In [7]:
lista[:5]

[5, 6, 9, 8, 7]

In [8]:
lista[4:]

[7, 4, 65, 2, 2, 56, 46, 54]

In [9]:
lista[:]

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]

In [10]:
import numpy as np

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [12]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
len(a)

4

In [14]:
min(a)

1

In [15]:
max(a)

4

In [16]:
b = np.array([[1,2,3],[5,6,4],[7,5,2]])
b

array([[1, 2, 3],
       [5, 6, 4],
       [7, 5, 2]])

In [17]:
b[0]

array([1, 2, 3])

In [18]:
b[:,1]

array([2, 6, 5])

In [19]:
b[2,2]

2

# Revisar la indexación de matrices (filas columnas)

In [20]:
b[0:2, 1:3]

array([[2, 3],
       [6, 4]])

In [21]:
a = np.random.rand(5,5)
a

array([[0.90342401, 0.58932142, 0.07324244, 0.27745889, 0.46021333],
       [0.38056811, 0.46400658, 0.35560715, 0.37066964, 0.74863922],
       [0.97563226, 0.85909419, 0.51710919, 0.45480557, 0.47062828],
       [0.93999803, 0.17216456, 0.58320958, 0.34955163, 0.63743231],
       [0.38397102, 0.19751437, 0.61551982, 0.42203672, 0.60067779]])

In [22]:
a.shape

(5, 5)

In [23]:
b  = np.random.rand(5,5)
b

array([[0.57549721, 0.1401788 , 0.3216924 , 0.99235767, 0.21671728],
       [0.70317268, 0.8270079 , 0.86263437, 0.06926561, 0.86429784],
       [0.77233483, 0.28551598, 0.39470395, 0.53811834, 0.26362553],
       [0.88237347, 0.07930512, 0.08502776, 0.79019215, 0.27037543],
       [0.06772661, 0.08943508, 0.70004735, 0.73246092, 0.67433324]])

In [24]:
a + b

array([[1.47892122, 0.72950022, 0.39493484, 1.26981656, 0.67693061],
       [1.0837408 , 1.29101448, 1.21824151, 0.43993524, 1.61293705],
       [1.74796709, 1.14461018, 0.91181314, 0.99292391, 0.73425381],
       [1.8223715 , 0.25146968, 0.66823734, 1.13974378, 0.90780774],
       [0.45169764, 0.28694945, 1.31556717, 1.15449764, 1.27501104]])

In [25]:
a-b

array([[ 0.3279268 ,  0.44914262, -0.24844996, -0.71489878,  0.24349606],
       [-0.32260457, -0.36300133, -0.50702722,  0.30140403, -0.11565862],
       [ 0.20329743,  0.57357821,  0.12240524, -0.08331277,  0.20700275],
       [ 0.05762456,  0.09285945,  0.49818183, -0.44064052,  0.36705689],
       [ 0.31624441,  0.10807929, -0.08452753, -0.3104242 , -0.07365545]])

In [26]:
a*b

array([[0.519918  , 0.08261037, 0.02356154, 0.27533846, 0.09973618],
       [0.2676051 , 0.38373711, 0.30675895, 0.02567466, 0.64704726],
       [0.75351478, 0.24528512, 0.20410504, 0.24473922, 0.12406963],
       [0.82942932, 0.01365353, 0.049589  , 0.27621296, 0.17234603],
       [0.02600506, 0.01766471, 0.43089302, 0.30912541, 0.40505701]])

In [27]:
a/b

array([[1.56981475, 4.20406957, 0.22767849, 0.27959565, 2.1235655 ],
       [0.54121573, 0.56106668, 0.41223392, 5.35142424, 0.86618199],
       [1.26322447, 3.00891803, 1.31011911, 0.8451776 , 1.7852151 ],
       [1.06530631, 2.17091367, 6.8590494 , 0.44236283, 2.35758228],
       [5.66942607, 2.20846639, 0.87925456, 0.57619009, 0.89077292]])

In [28]:
np.transpose(a)

array([[0.90342401, 0.38056811, 0.97563226, 0.93999803, 0.38397102],
       [0.58932142, 0.46400658, 0.85909419, 0.17216456, 0.19751437],
       [0.07324244, 0.35560715, 0.51710919, 0.58320958, 0.61551982],
       [0.27745889, 0.37066964, 0.45480557, 0.34955163, 0.42203672],
       [0.46021333, 0.74863922, 0.47062828, 0.63743231, 0.60067779]])

In [29]:
1/a

array([[ 1.10689996,  1.69686687, 13.65328614,  3.60413752,  2.17290532],
       [ 2.62765051,  2.15514186,  2.81209195,  2.6978201 ,  1.3357569 ],
       [ 1.02497636,  1.16401671,  1.93382755,  2.19874176,  2.12481918],
       [ 1.06383202,  5.80839628,  1.71464946,  2.86080769,  1.56879402],
       [ 2.6043632 ,  5.06292282,  1.62464305,  2.36946205,  1.66478603]])

## PROBLEMAS

1. Escribe una función **suma_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea la suma de las dos matrices originales. No utilices la operación de suma incorporada de NumPy (+).

In [30]:
import numpy as np

def suma_matrices(A, B):
   # Validar que las matrices tengan la misma dimensión
    if A.shape != B.shape:
        raise ValueError("Las matrices deben tener la misma dimensión para ser sumadas.")

    # Obtener las dimensiones de las matrices
    filas, columnas = A.shape

    # Crear una matriz vacía para almacenar la suma
    suma = np.empty((filas, columnas), dtype=int)

    # Iterar sobre los elementos de las matrices y sumarlos
    for i in range(filas):
        for j in range(columnas):
            suma[i, j] = A[i, j] + B[i, j]

    return suma

# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
assert np.array_equal(suma_matrices(A, B), np.array([[6, 8], [10, 12]]))

2. Escribe una función **transpuesta** que tome una matriz **NumPy** como argumento y **devuelva su transpuesta**. No utilices la propiedad T de NumPy.

In [31]:
import numpy as np

def transpuesta(A):
  # Obtener las dimensiones de la matriz de entrada
    filas, columnas = A.shape

    # Crear una matriz vacía con las dimensiones intercambiadas
    transpuesta_A = np.empty((columnas, filas), dtype=A.dtype)

    # Iterar sobre las filas y columnas originales
    for i in range(filas):
        for j in range(columnas):
            # Intercambiar filas por columnas al copiar los elementos
            transpuesta_A[j, i] = A[i, j]

    return transpuesta_A

# Pruebas
A = np.array([[1, 2, 3], [4, 5, 6]])
assert np.array_equal(transpuesta(A), np.array([[1, 4], [2, 5], [3, 6]]))

3. Escribe una función **multiplicar_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea el resultado de la multiplicación de las dos matrices originales. No utilices la operación de multiplicación de matrices incorporada de NumPy (@ o np.dot).

In [32]:
import numpy as np

def multiplicar_matrices(A, B):
   # Validar las dimensiones para la multiplicación matricial
    if A.shape[1] != B.shape[0]:
        raise ValueError("Las dimensiones de las matrices no permiten la multiplicación matricial.")

    # Obtener las dimensiones de las matrices de entrada
    filas_A, columnas_A = A.shape
    filas_B, columnas_B = B.shape

    # Crear una matriz vacía para el resultado
    resultado = np.empty((filas_A, columnas_B), dtype=A.dtype)

    # Realizar la multiplicación matricial
    for i in range(filas_A):
        for j in range(columnas_B):
            suma = 0
            for k in range(columnas_A):
                suma += A[i, k] * B[k, j]
            resultado[i, j] = suma

    return resultado

# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
assert np.array_equal(multiplicar_matrices(A, B), np.array([[4, 4], [10, 8]]))